name: sunntigsapp-ci
apiVersion: 2021-10-01
location: switzerlandnorth
properties:
  containers:
    - name: reverse-proxy
      properties:
        image: adcontainerregistry.azurecr.io/caddy:latest
        ports:
          - protocol: TCP
            port: 80
          - protocol: TCP
            port: 443
        resources:
          requests:
            memoryInGB: 1.0
            cpu: 1.0
          limits:
            memoryInGB: 1.0
            cpu: 1.0
        volumeMounts:
          - name: proxy-caddyfile
            mountPath: /etc/caddy
          - name: proxy-data
            mountPath: /data
          - name: proxy-config
            mountPath: /config
    - name: sunntigsapp
      properties:
        image: ${DeploymentImage}
        ports:
          - port: 3000
            protocol: TCP
        environmentVariables:
        - name: PORT
          value: 3000
        resources:
          requests:
            memoryInGB: 1.0
            cpu: 1.0
          limits:
            memoryInGB: 1.0
            cpu: 1.0
  imageRegistryCredentials: # Credentials to pull a private image
    - server:  adcontainerregistry.azurecr.io
      username: ${REGISTRY_USERNAME}
      password: ${REGISTRY_PASSWORD}
  restartPolicy: Never
  ipAddress:
    ports:
      - protocol: TCP
        port: 80
      - protocol: TCP
        port: 443
    type: Public        
    dnsNameLabel: neuerdnslabelsunntigsapp
  osType: Linux
  volumes:
    - name: proxy-caddyfile
      azureFile: 
        shareName: proxy-caddyfile
        storageAccountName: ${STORAGE_ACCOUNT_NAME}
        storageAccountKey: ${STORAGE_ACCOUNT_KEY}
    - name: proxy-data
      azureFile: 
        shareName: proxy-data
        storageAccountName: ${STORAGE_ACCOUNT_NAME}
        storageAccountKey: ${STORAGE_ACCOUNT_KEY}
    - name: proxy-config
      azureFile: 
        shareName: proxy-config
        storageAccountName: ${STORAGE_ACCOUNT_NAME}
        storageAccountKey: ${STORAGE_ACCOUNT_KEY}
