on: 
  push:
    branches:
      - main
name: main-deployment

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          STORAGE_ACCOUNT_KEY: ${{ secrets.STORAGE_ACCOUNT_KEY }}
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sunntigsapp:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sunntigsapp:${{ github.sha }}
        - name: 'Replace variables in deployment.yml'
          run: |
            export DeploymentImage=${{ secrets.REGISTRY_LOGIN_SERVER }}/sunntigsapp:${{ github.sha }}
            envsubst < yaml/deployment.yml > yaml/deployment-processed.yml
        
        - name: 'Deploy to Azure Container Instances'
          run: |
            az container create --resource-group ${{ secrets.RESOURCE_GROUP }} --file yaml/deployment-processed.yml 